# Generated by Django 2.1.4 on 2018-12-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
        migrations.RemoveField(
            model_name='music',
            name='video',
        ),
    ]
