# Generated by Django 2.1.4 on 2018-12-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181218_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d', verbose_name=''),
        ),
    ]
