# Generated by Django 2.1.4 on 2018-12-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20181219_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='video',
        ),
    ]
