# Generated by Django 2.1.4 on 2018-12-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_music_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d', verbose_name=''),
        ),
    ]
