# Generated by Django 2.1.4 on 2018-12-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20181220_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('release_date',)},
        ),
    ]
