# Generated by Django 2.1.4 on 2018-12-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20181221_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('-release_date',)},
        ),
    ]
